server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: Backend FMO
  jpa:
    database-platform: com.backendfmo.db.dialect.SQLiteDialect
    show-sql: false
  datasource:
    url: jdbc:sqlite:src/main/java/com/backendfmo/db/test.db
    driver-class-name: org.sqlite.JDBC
logging:
  file:
    name: auditoria-sistema.log
  level:
    root: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
